### ISSUE TITLE
Suggestions for merchant items to sell

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#45]
In order to better keep track of suggestions I am listing the suggested items players have given.

Please add your suggestions below and if I decide to use it I will list it above.

**Comment by Ulfengaard** [comment]
Cactus.

Man, Umbar is a luuoonng trip to get this stuff. Normally, I would be fine with that, but Decocraft is fairly integral to the pack and requires green dye to even get started.

Incidentally, those Black Numenoreans must really have wanted to get far, far away...

**Comment by GreatOrator** [comment]
Added to the list :D

**Comment by Brillik** [comment]
Ars Magica Flowers: Cerublossom, Aum, Wakeflower, Tarma Root, Desert Nova
Ars Magica Mobs:  Light Mages (for bonus mage posse stuff), 
Drop of Evil (to make cursed earth for all normal spawns)
Slime - only comes from jellyfish at the moment. And none of the other tinker's slimes are available.
Workable through woot spawners but otherwise very hard to get:
Blaze Rod, Ghast Tears, Magma Slime, Shulker items, Gunpowder
The other mob spawn drops are lootable from birdnests - would this be a cfg that would be easier to add to or would it saturate the system too much?

And it might be just me, but I cannot get verdant sprig to drop from fully grown crops for anything and it would be nice to be able to purchase those for Roots. 

A jukebox merchant might be fun too.

Hemp for the camping mod to make a bigger pouch.
An Apiarist who sells queens like the Jungle queen or silky propolis.
Sponges and necrotic bones for tinkers tools.

**Comment by GreatOrator** [comment]
Added most to the list, though the mob stuff should be fine now that I have turned back on mob spawning.  The camping mod stuff I am hesitant to add since there are still several crash bugs and still deciding on whether to leave it in or not because it does not look like the mod will be updated/fixed any time soon.

**Comment by GreatOrator** [comment]
Began Adding merchants to Bree which I can replicate to other locations once done (Bree has the largest market stall count so best place to get the variety going) 

Items on the list are now in the game (pending update of course) so just need some more ides :D

**Comment by Brillik** [comment]
An idea - a reliquary wizard selling very expensive reliquary items - 
- Coin of fortune, 
- Sojourners staff, 
- lantern of paranoia, 
- emperor's chalice, 
- Hero's Medallion, 
- Phoenix Down, 
- Kraken Shell, 
- Infernal Claws, etc. things that aren't super overpowered but helpful.  

Another "reliquary" idea for something less expensive but still rather hard to come by are the parts and pieces to make said items: 
- nebulous hearts, 
- slime pearls, 
- eye of the storm, 
- frozen core, 
- fertile essence, etc.   

I do wish Reliquary had an active inventory container where I could store all of its items but they'd stay active like they are present in the inventory without taking up more space, like the charm belt.

**Comment by Brillik** [comment]
If you wanted to make a Roots merchant there are a few items that would be nice to be able to purchase - some of them are simply hard to find vanilla items which might be better on another merchant:
- Old roots > Verdant sprig > Infernal bulbs > Dragon's Eye (listed in order of value)
- Prismarine Shard
- Sponge
- Poisonous Potato
- Red Sand

**Comment by Brillik** [comment]
Another item for the apothecary merchant is a very expensive "dragon's breath" bottle.

**Comment by GreatOrator** [comment]
I'll double check, but I think the only item in your list I have not put on a merchant already is the sand.  Thank you for the suggestions :D

**Comment by GreatOrator** [comment]
Though, does the dragon not spawn in the end?  I am mostly putting items that are unavailable in the merchants rather than making items easier to get...

**Comment by GreatOrator** [comment]
Merchants have been pretty stable at this point.  Closing this as it is of no more use to me.
