### ISSUE TITLE
BetterQuesting + Journeymap Integration

### ISSUE THREAD

**Issue by Brillik** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#47]
## Better Questing Suggestions
1. On the Location Tasks for the main quest lines, it would be very nice to have a button to either make waypoint, or print the location into the chat log as done with other locations like the job boards.  When working on a quest, the task shows its coordinates, and how far away it is, but falls short one step by importing that information to the map.  For example: Quest: Missing Rider - 2/3 Location Task - Black Steed - Location (13019, 39, 6457), Distance: from current position, Dimension: Overworld, Found/not Found - _**Make waypoint**_
2. In the Land of Middle Earth Quest lines, I greatly appreciate the teleport commands and greatly respect their cool down but there are a few times where I wish I knew where the location was to complete the area.  For instance, I just ran all over High Pass on my horse and never oncee completed the area.  I'm sure I missed the waypoint some place but its not listed on the quest.  If the location could be printed as it is with the location tasks in the quest log, and even better to have the "make waypoint" button available,  it'd be very nice to make sure I hit that spot before I leave.

**Comment by GreatOrator** [comment]
I had considered using the waypoint feature for all locations, but with so many I decided to only provide a few key ones and let the BQ one do the rest (having the specific coords with the distance) as the happy medium...mainly because by the time all is said and done, a player could end up with well over 100 waypoints from the main quest line alone.  I will see though if Funwayguy could possibly add that kind of integration for the Journeymap waypoints.
