### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by CmdrNorthpaw** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#68]
## Description
TolkienCraft seems great and fun, but there are a few issuses which I think need to be padded out...

- When you first spawn in the map, you are instructed to go see Aragorn. He tells you he wants you to see some people before getting started, and he will put their coordinates in your journal. But what is your journal? How do you get it?

- Elladan tells you that Nazgul have been spotted in Trollshaws, and that you have unlocked the "Trollshaws" waypoint to get there. But how do you get to Trollshaws? The stablemaster on the way to Elladan can't take you. This needs to be made clear

- There's no background in the BetterQuesting Questbook, on the main splash screen or in any of the questlines. Resetting the questbook doesn't help.

I did install the pack with MultiMC as opposed to the Twitch Launcher, if that helps.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: Latest
* TolkienCraft 3 version: Latest

## Crash report
```
null
```

**Comment by teagan75** [comment]
Well the coordinates show up in your chat after those conversations. Click it and it will be added to journeymap. Pretty sure it tells you to do that :D

**Comment by CmdrNorthpaw** [comment]
It did do that but only when Elrond asked me to visit Elladan's camp

**Comment by teagan75** [comment]
Isn’t that in the Trollshaws? Or are you talking about the quest given at the camp. I think if you follow the roads they will lead you if the coords are unclear

**Comment by GreatOrator** [comment]
Journal is the BQ quest book, the quest line is in the scholars of middle earth.  The way point is the elledan's camp waypoint that shows up in chat, teleporting is enabled to use with journeymap, if images are not showing, are you on an apple pc?  there is a known issue with how apple computers read the paths requested for images in BQ.

**Comment by CmdrNorthpaw** [comment]
Okay, thanks. Yes, I do play on a Mac. Is there a workaround?

Also, all the quests in the Scolars questine are locked by the "Getting Started" quest, which doesn't seem to exist.

**Comment by GreatOrator** [comment]
You have to speak to aragorn first, he unlocks that quest line, and sadly not currently.  Funwayguy has been trying though.

**Comment by CmdrNorthpaw** [comment]
New issue: I _cannot_ complete the Knowledge of the Giants II NPC quest! I viseted that giant and killed him multiple times. :confused:

**Comment by GreatOrator** [comment]
Have you checked the BQ quest book as well?  most quests require both (usually because hidden auto quest for a command or something)

**Comment by CmdrNorthpaw** [comment]
I've done both location tasks in Aid of Mirkwood but can't complete the final KOG 2 NPC Quest task

**Comment by GreatOrator** [comment]
I'll take a look at this later today to make sure.  If i find anything unusual I'll either give you the way to fix or push out an update.

**Comment by GreatOrator** [comment]
So have you gone back to Barachen's Camp and tried speaking to him? Actually, reading over the dialog of the quest, have you gone back to elledan's camp to speak to him?

**Comment by GreatOrator** [comment]
If you are still having issues, reopen a new issue please.  Closing this one.

**Comment by tgevrenos** [comment]
This issue was closed a while ago but I just wanted to share my experience, which might be useful. 

I am also playing on a mac, I tried this all both on osx and windows sides, (I use bootcamp), the issue continues.

Thus, like OctoPenguin, i've been playing around with the config files & etc. figured out that, 

1- Turning on edit mode on better questing, and one by one editing all the visuals paths from this "\" to this "/", fixes the issue of visual not showing up properly.

2- also on edit mode i erased the second part of the "full knowledge" quest the one that requires talking with aragorn once again after talking to all the scholars, that one seems to be the issue for me. thus that worked and all relevant quest unlocked as they should. 

hope this helps to anyone that might have similar issues. This topic guided me well.. 

PS. I've played Tolkiencraft 2 for like ages, I've just started playing this and will always be saying, keep up the great work GreatOrator, I truly admire and enjoy all your creations and the immersion you create.

**Comment by GreatOrator** [comment]
Well, with aragorn you are intended to go speak and collect all the quests for scholars first, that is why they do not unlock right away.  Within the last few updates this should have been tweaked to be more obvious, as for the slash issue, that has been reported to funwayguy, he has just been busy with BQ3 so it is low priority as a fix at the moment.
