### ISSUE TITLE
Troubles of rivendell

### ISSUE THREAD

**Issue by 8qBITs** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#86]
No crash report,
Quest is just broken i can't manage to do the 2nd part as npc wont give me option to speak further http://i.8qbit.me/j7qQn.png

**Comment by GreatOrator** [comment]
Assumng this is the same person from my discord, if you had searched for this you would have found a pinned comment for exactly this quest.

if it is getting stuck at the second dialog after the selection of "It indeed was a long journey, especially the river crossing."
you'll need to go in to edit mode (use the NPC Wand)
Then right click on aragorn, go to global, dialogs, CH1-Chasing Shadows, Troubles of Rivendell II, availability options, change the faction section to always, then go to Troubles of Rivendell III, availability options, select quest, change to always
after you exit out, should have the full dialog set.  I think what happened is I originally was using faction standing to trigger quests, later changed it but forgot to change the availability.  Because I already had the faction standing it always worked for me which is why I never had the issue
